const subcategories = {
  despesas: [
    { title: 'Fretes e transportes' },
    { title: 'Perdas nos recebimentos de créditos' },
    { title: 'SPC - Serviço de Proteção ao Crédito' },
    { title: 'Taxa de administração de cartões de crédito' },    
    { title: 'Assistência médica' },
    { title: 'Contribuição sindical' },
    { title: 'Férias e adicionais' },
    { title: 'FGTS' },
    { title: 'Indenizações' },
    { title: 'INSS' },
    { title: 'IRRF retido trabalho assalariado' },
    { title: 'PIS folha de pagamento' },
    { title: 'Salários e adicionais' },
    { title: 'Seguro de vida' },
    { title: 'Uniformes e materiais de proteção'},
    { title: 'Vale transporte' },
    { title: 'Encargos financeiros' },
    { title: 'Tarifas bancárias' },
    { title: 'Multas' },
    { title: 'Juros' },
    { title: 'ICMS' },
    { title: 'Impostos, multas e taxas diversas' },
    { title: 'IOF' },
    { title: 'IPTU' },
    { title: 'IPVA' },
    { title: 'IRPF' },
    { title: 'IRRF s/aluguel' },
    { title: 'IRRF s/aplicação' },
    { title: 'ITR' },
    { title: 'Issqn' },
    
    { title: 'Parcelamento ICMS' },
    { title: 'Parcelamento Previdenciário' },
    { title: 'Parcelamento de Impostos Federais' },
    { title: 'Parcelamento Simples Nacional' },
    { title: 'Taxa ISSQN/TFLF/DAMSP' },
    { title: '13º salário e adicionais' },
    { title: 'Férias e adicionais' },
    { title: 'Retirada pró-labore' },
    { title: 'Água e Esgoto' },
    { title: 'Assinaturas de Jornais, boletins etc.' },
    { title: 'Brindes, contribuições e donativos' },
    { title: 'Cartório, xerox e autenticações' },
    { title: 'Combustíveis e lubrificantes' },
    { title: 'Comissões' },
    { title: 'Conservação do imóvel' },
    { title: 'Correios e Telégrafos' },
    { title: 'Cursos e treinamentos' },
    { title: 'Depreciações de imobilizados' },
    { title: 'Despesas de Aluguel' },
    { title: 'Diárias de viagem' },
    { title: 'Diárias de viagens, lanches e refeições' },
    { title: 'Energia elétrica' },
    { title: 'Gastos com informática' },
    { title: 'Honorários Contábeis' },
    { title: 'Internet' },
    { title: 'Manutenção e Reparos' },
    { title: 'Materiais de embalagens' },
    { title: 'Copa e Cozinha' },
    { title: 'Material de escritório' },
    { title: 'Material de limpeza' },
    { title: 'Material de uso e consumo' },
    
    { title: 'Outros fretes e transportes' },
    { title: 'Pedágio' },
    { title: 'Perdas de estoques '},
    { title: 'Propaganda, publicidade e patrocínio' },
    { title: 'Reformas em edificações' },
    { title: 'Seguros' },
    { title: 'Serviços autônomos' },
    { title: 'Telecomunicação' },
    { title: 'Acordos Judiciais' },
    { title: 'Multas por infrações fiscais' },
    { title: 'Perda de capital na venda de imobilizado' },
    { title: 'Multas por infrações de trânsito' },
    { title: 'Investimento' }, 
    { title: 'Mercadorias para Revenda'},
    { title: 'Antecipação de Dividendos'},
    { title: 'Outras despesas' },
  ],
  receitas: [
    { title: 'Vendas' },
    { title: 'Prestação de Serviço' },
    { title: 'Rendimento Financeiro' },
  ],
  ativos: [
    { title: 'Máquinas e Equipamento' },
    { title: 'Móveis e Utensílios' },
    { title: 'Instalações' },
    { title: 'Veículos' },
    { title: 'Imóveis' },
    { title: 'Terreno' },
  ]
}

export default subcategories;